version: '3.7'
services: 
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  craft:
    image: craftcms
    build:
      context: .
    restart: unless-stopped
    depends_on: 
      - mysql
    environment: 
      LOCAL_UID: 1000
      CONFIGURATION: production
      SITE_NAME: jamesgreenaway.me
      EMAIL: greenaway.james@gmail.com
      SSL_CERTIFICATE_NAME: Craft
      REDIS_HOST: redis
    ports: 
      - "443:443"
      - "80:80"
    volumes: 
      - letsencrypt:/etc/letsencrypt/
      - ./craft:/var/www/html/
      - ./virtualhost.conf:/tmp/000-default.conf
  redis:
    image: redis:4-alpine
    volumes:
      - redis:/data
volumes: 
  mysql: {}
  redis: {}
  letsencrypt: {}