version: '3.7'
services: 
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  craft:
    image: craftcms
    build:
      context: .
    restart: unless-stopped
    depends_on: 
      - mysql
    environment: 
      LOCAL_UID: 1000
      APACHE_SERVER_NAME: localhost
      SSL_SITE_NAME: Craft
    ports: 
      - "5000:443"
      - "8080:80"
    volumes: 
      - ./craft:/var/www/html/
volumes: 
  mysql: {}
