version: '3'
services: 
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes: 
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    container_name: mysql
  php-apache:
    build:
      context: .
    image: jamesgreenaway/crafcms:1.0
      args:
        UID: 1000
        SITE_NAME: Craft
    restart: unless-stopped
    depends_on: 
      - mysql
    environment: 
      - APACHE_DOCUMENT_ROOT=/var/www/html/web
    ports: 
      - "5000:443"
      - "8080:80"
    volumes: 
      - ./craft:/var/www/html/
    container_name: craft
volumes: 
  mysql: {}
