version: "3.7"
services:
  craft:
    image: craftcms
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    user: craft
    volumes:
      - ./craft:/var/www/html/
      - ./virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - type: bind
        source: /Users/home/.composer/
        target: /home/craft/.composer/
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=web-secure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=https
      - traefik.http.middlewares.https.redirectscheme.scheme=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(
        `${COMPOSE_PROJECT_NAME}.test`, `www.${COMPOSE_PROJECT_NAME}.test`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=Host(
        `${COMPOSE_PROJECT_NAME}.test`, `www.${COMPOSE_PROJECT_NAME}.test`)
    networks: 
      - traefik
networks:
  traefik:
    external: true