version: "3.7"
services:
  craft:
    image: craftcms
    build:
      context: .
    restart: "no"
    env_file: .env
    volumes:
      - traefik:/tmp/traefik
      - ./craft:/var/www/html/
      - ./virtualhost.conf:/tmp/virtualhost.conf
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=web-secure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=https
      - traefik.http.middlewares.https.redirectscheme.scheme=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(
        `${COMPOSE_PROJECT_NAME}.test`, `www.${COMPOSE_PROJECT_NAME}.test`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=Host(
        `${COMPOSE_PROJECT_NAME}.test`, `www.${COMPOSE_PROJECT_NAME}.test`)
    networks: 
      - traefik
networks:
  traefik:
    external: true
volumes:
  traefik:
    external: true